### ISSUE TITLE
Make encoded biscuit editable and block display not editable in bc-token-printer

### ISSUE THREAD

**Issue by divarvel** [biscuit-auth/biscuit-web-components#1]
The `<code>` block could be turned into a `<textarea>`, so that people can paste tokens to inspect them. Following the same idea, the blocks displaying datalog should not be editable (since the encoded token can't be re-created). Using the editor is still useful though (unless there is a simple way to get line numbers and syntax highlighting without an editor).

Idk if it's doable to plug authorization to the token printer in the current state of things, but that would be a nice addition to a printer with user input.

**Comment by clementd-fretlink** [comment]
Done in https://github.com/biscuit-auth/biscuit-web-components/pull/5
