### ISSUE TITLE
Better support for dark mode

### ISSUE THREAD

**Issue by ptitfred** [biscuit-auth/biscuit-web-components#26]
Successes are highlighted with a light background and that doesn't work well with the font color when the website is in dark mode:

![image](https://user-images.githubusercontent.com/346377/202851881-33530bc6-ff10-471d-bf4d-37d9c690b91b.png)

For success, it's currently defined [here](https://github.com/biscuit-auth/biscuit-web-components/blob/main/src/bc-datalog-editor.js#L112-L114). Maybe other marks should be tweaked too, I'm not sure.

**Comment by ptitfred** [comment]
Overriding the color for this mark could do the trick:

```css
color: var(--bs-gray-dark);
```

**Comment by ptitfred** [comment]
Maybe tweaking the background-color can help too:

```css
background: rgb(134, 227, 134);
```

This color has been hand picked and might not be consistent with the rest of the palette.

**Comment by jtanguy** [comment]
Maybe we could use classes in marks and tweak the color in css https://codemirror.net/docs/ref/#view.Decoration^mark^spec.class

**Comment by divarvel** [comment]
#29 should fix it. Feel free to suggest better colors
